blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('aboutus/', views.aboutus,name='aboutus'),
    path('home/', views.home,name='home'),
    path('contactus/', views.contactus,name='contactus'),
    path('signuppage/', views.signuppage,name='signuppage'),
    path('loginpage/', views.loginpage,name='loginpage'),
    path('dashboard/', views.dashboard,name='dashboard'),
    path('logoutpage/', views.logoutpage,name='logoutpage'),  
    path('addpost/', views.addpost,name='addpost'),
    path('editpage/<int:id>', views.edit_page,name='editpage'),
    path('deletepage/<int:id>', views.delete_page,name='deletepage'),

    

]

miniblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

]+ static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from tinymce.models import HTMLField
from ckeditor.fields import RichTextField


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    imagefields = models.FileField(upload_to= 'images/')
    describe = RichTextField()
    date = models.DateField()

blog/forms.py
from django import forms
import datetime
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Blog

class Signup(UserCreationForm):
    email = forms.CharField(widget=forms.EmailInput,required=True)
    first_name = forms.CharField(required=True)
    password2 = forms.CharField(widget=forms.PasswordInput,label='confirm password')
    class Meta:
        model = User
        # fields = '__all__'
        fields = ['username','first_name','last_name','email']
        labels = {'email':'Email'}

# R9865177862


class Blogform(forms.ModelForm):
    date = forms.DateField(label="publish date",initial = datetime.date.today())
    class Meta:
        model = Blog
        fields =['title','imagefields','describe','date']

blog/views.py
from django.shortcuts import render,HttpResponseRedirect
from .forms import Signup,Blogform
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,login,logout,update_session_auth_hash
from .models import Blog
from django.contrib.auth.models import User
import os

# Create your views here.

def aboutus(request):
    return render(request , 'aboutus.html')

def home(request):
    forms =Blog.objects.all()
    return render(request , 'home.html',{"form":forms})

def contactus(request):

    return render(request, 'contactus.html')

def dashboard(request):
    if request.user.is_authenticated:
        data = Blogform()
        result = Blog.objects.all()
        username = request.user.username
            
        return render(request, 'dashboard.html',{'form':data,'result':result,'username':username})
    else:
        return HttpResponseRedirect('/loginpage/')

def addpost(request):
    username = request.user.username
    if request.method=="POST":
        form = Blogform(request.POST , request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/dashboard/")
    else:
        form = Blogform()
    return render(request , 'addpost.html',{"form":form,'username':username})

def signuppage(request):
    if not request.user.is_authenticated:
        if request.method=="POST":
            form = Signup(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/loginpage/')
        else:    
            form = Signup()
        return render(request , 'signup.html' , {'form':form})
    else:
        return HttpResponseRedirect('/dashboard/')

def loginpage(request):
    if not request.user.is_authenticated:
        if request.method=="POST":
            form = AuthenticationForm(request = request,data=request.POST)
            if form.is_valid():
                username= form.cleaned_data['username']
                password= form.cleaned_data['password']
                user = authenticate(username = username , password = password)
                if user!=None:
                    login(request, user)
                    return HttpResponseRedirect('/dashboard/')

        else:
            form = AuthenticationForm()
        return render(request, 'login.html', {'form':form})
    else:
        return HttpResponseRedirect('/dashboard/')


def logoutpage(request):
    logout(request)
    return render(request, 'home.html')

def edit_page(request,id):
    if request.user.is_authenticated:
        if request.method=="POST":
            data = Blog.objects.get(pk=id)
            form = Blogform(request.POST,request.FILES , instance=data)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/dashboard/')

        else:
            data = Blog.objects.get(pk=id)
            form = Blogform(instance=data)
        return render(request, 'edit.html',{'form':form})
    else:
        return HttpResponseRedirect('/loginpage/')

def delete_page(request,id):
    data = Blog.objects.get(pk=id)
    if len(data.imagefields)>0:
        os.remove(data.imagefields.path)
    data.delete()
    return render(request,'dashboard.html')

blog/templates/aboutus.html
{% extends 'base.html' %}

{% block content %}
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur fugiat omnis consequuntur ut non atque dolor tempore neque laboriosam iste minima voluptatum architecto quas harum fugit, quibusdam sequi repellendus. Cumque.
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Est, doloribus repudiandae consequatur, cum alias dignissimos ullam quos eum enim illum officiis sed eveniet similique dolorum dolor voluptatem quaerat soluta iusto?

    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit quis commodi quidem accusantium blanditiis deserunt molestiae, veritatis rem quo enim ratione placeat obcaecati sit at nobis incidunt aspernatur similique possimus.
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sequi accusantium voluptates nemo at culpa voluptas error mollitia. Veritatis doloribus asperiores excepturi possimus, quo, soluta, suscipit optio minus quas dolorem nulla!
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero nesciunt maiores iste commodi. Aut excepturi ex consectetur numquam aperiam dolore non vero nulla odio, obcaecati repellendus esse, et ut corporis?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quia dolores labore laudantium ipsa aut eius cumque. Aliquam, debitis aliquid! Est iure repellendus architecto quas aspernatur modi praesentium dolor provident.
    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Pariatur porro delectus deleniti doloribus eveniet necessitatibus quia labore eligendi reiciendis iusto officia odio, minus amet optio inventore quos quo dolor est?
    
{% endblock content %}
    

blog/templates/addpost.html
{% extends 'base.html' %}

{% block content %}
<h3>Welcome {{username}}</h3>
    <form method="POST"enctype="multipart/form-data"  novalidate>
        {% csrf_token %}

        {{form.media}}
        {% for form in form %}
        {{form.label}} {{form}}{{form.errors|striptags}} <br><br>
        {% endfor %}
        <input type="submit" value="submit">
    </form>

{% endblock content %}

blog/templates/base.html
{% include "navbar.html" %}

{% block content %}
    
{% endblock content %}
    

blog/templates/contactus.html
{% extends 'base.html' %}


{% block content %}
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores temporibus ab nemo voluptas quisquam ipsa dignissimos, delectus distinctio blanditiis porro recusandae. Ab cumque magnam est consequuntur. Pariatur debitis quis cupiditate.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis architecto perferendis saepe! Dolores excepturi incidunt facilis dolore. Molestiae magnam adipisci quasi aspernatur minus. Explicabo eaque repudiandae consequuntur voluptate corporis expedita!Lorem
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vitae, iusto repellat modi a hic inventore maxime tempore aliquam velit commodi temporibus animi autem, dicta eveniet minus rem vero. Sunt, laudantium.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni amet ducimus quaerat molestiae optio! Ut quos suscipit hic aspernatur perferendis numquam officia repellendus eligendi mollitia, repudiandae esse consequatur minima molestias.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum officia earum dolorum pariatur consequuntur architecto iusto neque perferendis. Magnam modi est deserunt sit nulla, libero amet quas quo ad unde!magnam
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum amet harum natus nesciunt earum, laudantium nemo expedita. Rerum, eveniet at. Ipsam id consequuntur alias magnam est aspernatur perspiciatis porro doloribus?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum id officiis temporibus veritatis voluptatum vel veniam. Culpa quis deleniti voluptatem, fugiat optio sit rerum vitae illo dolores accusantium laborum labore!
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, fuga praesentium voluptatum provident mollitia consectetur delectus dignissimos asperiores odit voluptas libero eos fugiat similique ab maiores beatae eaque labore. Ratione!
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. A ex architecto autem pariatur doloribus dignissimos natus saepe? Minima alias vitae sunt, aliquam, aliquid animi obcaecati possimus maiores quae dolore saepe.
    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo veritatis veniam ea error, fugiat totam corporis nostrum, iusto blanditiis possimus hic obcaecati provident dolorum dignissimos debitis necessitatibus perspiciatis. Perspiciatis, ipsam!
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur autem rem amet ab. Earum, rerum fuga, sed eius corrupti eveniet laudantium adipisci fugit maxime modi quos commodi, cupiditate cum perspiciatis?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas odio placeat non expedita facilis blanditiis molestias natus in, error sed tenetur optio, atque veniam. Beatae totam saepe mollitia sapiente molestiae!
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione ipsa ut assumenda veritatis excepturi optio, et earum nemo ullam pariatur vero mollitia dignissimos nesciunt odio. Tenetur ratione minima ea sapiente.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio nisi autem quae laudantium nam facilis vero? Eaque corporis accusamus iure inventore autem, ut laboriosam recusandae? Sed illum ducimus voluptates omnis!
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut ab quos mollitia sed, soluta doloremque? Ullam, earum magnam necessitatibus enim perspiciatis eum ducimus, magni adipisci hic praesentium nobis odio esse!
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt perspiciatis aliquam rem at, id magni molestiae sequi incidunt, laborum, consequuntur et obcaecati repudiandae quia inventore vel quo officiis. Praesentium, tempora.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam quibusdam quas expedita nobis velit, cumque consequuntur consequatur libero excepturi porro corporis asperiores rem, recusandae culpa aspernatur et, eius totam sed.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut dolores repellat voluptates perferendis reprehenderit suscipit ullam, distinctio odio id, ipsam nihil officiis. Dolorum beatae molestias consequuntur harum unde! Tenetur, numquam.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos doloremque ad, deserunt sequi eos magni, porro vero accusantium maxime a quos culpa dolore aspernatur nemo architecto similique. Placeat, enim ea!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut nobis, excepturi perspiciatis ea asperiores reiciendis molestias, cupiditate sequi ad blanditiis aperiam mollitia. Illo dolores modi tenetur molestias, mollitia non consequuntur.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem nobis id temporibus. Nulla mollitia, porro consectetur hic magnam vero sint pariatur itaque velit aspernatur, consequuntur voluptatum enim at, alias quas.
    
{% endblock content %}
    

blog/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<h3>Welcome {{username}}</h3>
{% if perms.blog.add_blog %}
<a href="{% url 'addpost'%}"><button>add post</button></a>
{% endif %}
            <table>
                <tr>
                  <th>title</th>
                  <th>describe</th>
                  <!-- <th>imagefields</th> -->
                  <th>date</th>
                  {% if perms.blog.delete_blog and perms.blog.change_blog  %}
                  <th>operation</th>
                  {% endif %}
                </tr>
               
                    {% for result in result %}
                 <tr>        
                        <th>{{result.title}}</th>
                        <!-- <th>{{result.imagefields}}</th> -->
                        <th>{{result.describe|safe}}</th>                    
                        <th>{{result.date}}</th>
                        {% if perms.blog.delete_blog and perms.blog.change_blog %}
                        <th><a href="{% url 'editpage' result.id%}"><button>edit</button></a>
                          <a href="{% url 'deletepage' result.id%}"><button>delete</button></a>
                        {% endif %}

                </tr>      
                    {% endfor %}
                    
                
            </table>
{% endblock content %}

blog/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<h3>Welcome {{username}}</h3>
    <form method="POST"enctype="multipart/form-data"  novalidate>
        {% csrf_token %}

        {{form.media}}
        {% for form in form %}
        {{form.label}} {{form}}{{form.errors|striptags}} <br><br>
        {% endfor %}
        <input type="submit" value="submit">
    </form>

{% endblock content %}

blog/templates/home.html
{% extends 'base.html' %}


{% block content %}
    {% for form in form %}
        {{form.title}} <br><br>
        <img src="/media/{{ form.imagefields }}" width="600" height="700"><br><br>
        {{form.describe|safe}}<br><br>
        {{form.date}}<br><br>
    {% endfor %}

{% endblock content %}
    

blog/templates/login.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <a href="{% url 'loginpage'%}"><button>login</button></a>
    </form>
{% endblock content %}
    

blog/templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <style>
      table, th, td {
        border: 1px solid white;
        border-collapse: collapse;
      }
      th, td {
        background-color: #96D4D4;
      }
      </style>

</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">mini blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'home' %}">Home </a>
            <a class="nav-item nav-link" href="{% url 'aboutus' %}">about us</a>
            <a class="nav-item nav-link" href="{% url 'contactus' %}">Contact us</a>
            {% if not request.user.is_authenticated %}
            <a class="nav-item nav-link " href="{% url 'loginpage' %}">login</a>
            <a class="nav-item nav-link " href="{% url 'signuppage' %}">signup</a>

            {% else %}
            <a class="nav-item nav-link" href="{% url 'dashboard' %}">dashboard </a>
            <a class="nav-item nav-link " href="{% url 'logoutpage' %}">logout</a>
            
            {% endif %}
          </div>
        </div>
      </nav>



    <script src="{% static 'js/jquery.js'%}"></script>
    <script src="{% static 'js/popper.js'%}"></script>
    <script src="{% static 'js/bootstrap.js'%}"></script>
</body>
</html>

blog/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for form in form %}
          {{form.label_tag}} {{form}}  {{form.errors|striptags}} <br><br>
        {% endfor %}
        
        <a href=""><button type="submit">signup</button></a>

    </form>

{% endblock content %}
    